# Travis CI Configuration File

language: php

# Build matrix options
matrix:
  include:
    - php: 7.3
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 7.3
  fast_finish: true

before_install:
  - chmod +x build.sh

install:
  - composer install

script: ./build.sh