language: node_js
node_js:
- 12
addons:
  ssh_known_hosts:
  - 18.135.214.64
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
install:
- npm install
script:
- echo "hello world"
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: main
