language: php
matrix:
  include:
  - php: 7.3
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
  - php: 7.3
  fast_finish: true
addons:
  ssh_known_hosts:
  - 18.169.162.13
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- sudo apt-get install -y nodejs
install:
- composer install
- npm install
script:
- npm run bundle
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: main
